### ISSUE TITLE
Q: Has the exported xpub BIP-32 path bug been fixed?

### ISSUE THREAD

**Issue by gurnec** [mycelium-com/wallet-ios#10]
Just curious really.... has the bug mentioned here been fixed, and do you happen to know the version (or commit if that's easier) when it was fixed?

<https://bitcointalk.org/index.php?topic=965932.msg10564840#msg10564840>

Thanks!

**Comment by dabura667** [comment]
I just checked the most recent appstore version.

No it is not fixed yet.

**Comment by gurnec** [comment]
@dabura667 Thank you taking the time to check.

**Comment by andrewtoth** [comment]
Fixed in v1.4
