### ISSUE TITLE
Add hide keypad option on send and receive window 

### ISSUE THREAD

**Issue by partsoven** [mycelium-com/wallet-ios#2]
Hey @mycelium-com. I have started using this app on my iphone and it seems to really work great! One thing I noticed though is that when I bring up either the send or receive window the address is covered by the keyboard. I figured out after some minor frustration you can click off the keyboard and it will hide. I think it may be more user friendly to either have the send and receive actions be put into steps or to have a clear option to hide the keyboard.

**Comment by Giszmo** [comment]
Now this is an old issue :D I bet it is resolved meanwhile. If not, comment and I open it again. (Have no iPhone myself)
