### ISSUE TITLE
Write cost in BTC when receive payment

### ISSUE THREAD

**Issue by chiliec** [mycelium-com/wallet-ios#22]
When I want to receive money, I can share only one currency I choose:
```
Please send 1,500.00 RUB to 1MzR2oac6qgJVG7CsPvupsb7KMmnf6jCtM
```
Maybe it's worth to add cost in BTC like
```
Please send 1,500.00 RUB (0.25877599 BTC) to 1MzR2oac6qgJVG7CsPvupsb7KMmnf6jCtM

**Comment by Giszmo** [comment]
Please elaborate. When I send a payment request of 3000CLP, the email only contains the BTC value, not the fiat value one purpose, as there is no way of sending fiat on the bitcoin network.

**Comment by Chiliec** [comment]
I used telegram for share text, but I think it's no matter. When choose fiat currency, text contains fiat value and only it.

**Comment by Giszmo** [comment]
Ooops. My bad. This is iOS, not Android.

**Comment by Giszmo** [comment]
Thanks for reporting this. Payment requests in fiat make little sense and in Android we don't write the fiat value at all.
