### ISSUE TITLE
My money vanished from my wallet 

### ISSUE THREAD

**Issue by Naube86** [mycelium-com/wallet-ios#34]
After I sent two successful transactions that was only one forth of the money that was in my wallet, my money vanished from my account. My transaction history proves that the math doesn’t add up. PLEASE HELP!!!

**Comment by Giszmo** [comment]
Please contact us at support@mycelium.com with issues that require more private communication. Please provide screenshots and/or transaction IDs.

**Comment by Wipahporn** [comment]
Thang

**Comment by Diamantem** [comment]
Ustedes los de soporte de mycelium nunca responden a los correos de ayuda de sus usuarios. He enviado diversos correo pidiendo ayuda para recuperar mi saldo que desapareció después de cancelar una transacción sin confirmar y hasta el momento no he tenis respuesta. Aclaro que la transacción decía error en coneccion al servidor por lo que se puso en cola y no de realizo confirmación alguna. Por lo que decidí cancelarla y tanto el saldo como el historial desaparecio
