### ISSUE TITLE
Support different currency than USD

### ISSUE THREAD

**Issue by prusnak** [mycelium-com/wallet-ios#4]
Android version supports different currencies than USD. (Probably by fetching some exchange rate and recalculating USD values into local ones).

**Comment by oleganza** [comment]
There is already internal machinery to support multiple currencies. Due to time constraints of v1.0, there is no UI for selecting a currency. This will be supported in one of future updates.

**Comment by warijo** [comment]
This please.

**Comment by Jop-V** [comment]
This should be closed right?

**Comment by warijo** [comment]
Yes, I think so, too.
