### ISSUE TITLE
Protect critical operations with PIN code

### ISSUE THREAD

**Issue by prusnak** [mycelium-com/wallet-ios#5]
Android version protects some (critical) operations with an optional PIN code. These are, for example: sending transaction, exporting private seed for backup.

**Comment by oleganza** [comment]
I recommend going straight to system API using Touch ID / system passcode to authenticate each payment. Not sure about custom per-wallet password. That could be a fun option for securing 90% of the funds while having 10% easily accessible with just Touch ID for user's convenience.

**Comment by PacificaShip** [comment]
Yes, PLEASE implement this. I just made a transfer and realised Mycelium wasn't asking for any identification. I think that made me shiver a little bit

**Comment by Giszmo** [comment]
I think this is fixed since years. Not an iOS guy myself but touch id is used in the iOS verison of our wallet.
